<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Differential Item Functioning per item politomici | Guida pratica alla calibrazione, allo studio dell’invarianza e allo scoring di strumenti psicologici tramite l’Item Response Theory (IRT) in R</title>
  <meta name="description" content="Differential Item Functioning per item politomici | Guida pratica alla calibrazione, allo studio dell’invarianza e allo scoring di strumenti psicologici tramite l’Item Response Theory (IRT) in R" />
  <meta name="generator" content="bookdown 0.37 and GitBook 2.6.7" />

  <meta property="og:title" content="Differential Item Functioning per item politomici | Guida pratica alla calibrazione, allo studio dell’invarianza e allo scoring di strumenti psicologici tramite l’Item Response Theory (IRT) in R" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Differential Item Functioning per item politomici | Guida pratica alla calibrazione, allo studio dell’invarianza e allo scoring di strumenti psicologici tramite l’Item Response Theory (IRT) in R" />
  
  
  

<meta name="author" content="a cura di Francesco Sanson" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="calibrazione-di-strumenti-unidimensionali-con-item-politomici.html"/>
<link rel="next" href="scoring-di-strumenti-unidimensionali-politomici.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Guida IRT</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="introduzione-alla-guida.html"><a href="introduzione-alla-guida.html"><i class="fa fa-check"></i>Introduzione alla guida</a></li>
<li class="chapter" data-level="" data-path="installare-i-pacchetti.html"><a href="installare-i-pacchetti.html"><i class="fa fa-check"></i>Installare i pacchetti</a></li>
<li class="chapter" data-level="" data-path="calibrazione-di-strumenti-unidimensionali-con-item-dicotomici.html"><a href="calibrazione-di-strumenti-unidimensionali-con-item-dicotomici.html"><i class="fa fa-check"></i>Calibrazione di strumenti unidimensionali con item dicotomici</a></li>
<li class="chapter" data-level="" data-path="differential-item-functioning-per-modelli-dicotomici.html"><a href="differential-item-functioning-per-modelli-dicotomici.html"><i class="fa fa-check"></i>Differential Item Functioning per modelli dicotomici</a></li>
<li class="chapter" data-level="" data-path="scoring-di-strumenti-unidimensionali-con-item-dicotomici.html"><a href="scoring-di-strumenti-unidimensionali-con-item-dicotomici.html"><i class="fa fa-check"></i>Scoring di strumenti unidimensionali con item dicotomici</a></li>
<li class="chapter" data-level="" data-path="calibrazione-di-strumenti-unidimensionali-con-item-politomici.html"><a href="calibrazione-di-strumenti-unidimensionali-con-item-politomici.html"><i class="fa fa-check"></i>Calibrazione di strumenti unidimensionali con item politomici</a></li>
<li class="chapter" data-level="" data-path="differential-item-functioning-per-item-politomici.html"><a href="differential-item-functioning-per-item-politomici.html"><i class="fa fa-check"></i>Differential Item Functioning per item politomici</a></li>
<li class="chapter" data-level="" data-path="scoring-di-strumenti-unidimensionali-politomici.html"><a href="scoring-di-strumenti-unidimensionali-politomici.html"><i class="fa fa-check"></i>Scoring di strumenti unidimensionali politomici</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Guida pratica alla calibrazione, allo studio dell’invarianza e allo scoring di strumenti psicologici tramite l’Item Response Theory (IRT) in R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="differential-item-functioning-per-item-politomici" class="section level1 hasAnchor">
<h1>Differential Item Functioning per item politomici<a href="differential-item-functioning-per-item-politomici.html#differential-item-functioning-per-item-politomici" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>La procedura per lo studio dell’invarianza a livello di item calibrati tramite il modello graded è la medesima illustrata per il modello 2PL.</p>
<p>Di seguito verrà illustrata l’invarianza di genere della scala TEST.POLY, utilizzando la varibile SESSO (1=maschio, 2=femmina).</p>
<p>Per prima cosa selezioniamo la variabile gruppo.</p>
<div class="sourceCode" id="cb95"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb95-1"><a href="differential-item-functioning-per-item-politomici.html#cb95-1" tabindex="-1"></a>GRUPPO<span class="ot">&lt;-</span><span class="fu">as.factor</span>(TEST.POLY<span class="sc">$</span>SESSO) <span class="co">#var. gruppo</span></span></code></pre></div>
<p>Selezioniamo poi gli item sui quali condurre l’invarianza.</p>
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb96-1"><a href="differential-item-functioning-per-item-politomici.html#cb96-1" tabindex="-1"></a>item.DIF.graded<span class="ot">&lt;-</span>TEST.POLY[,<span class="dv">2</span><span class="sc">:</span><span class="dv">7</span>]  <span class="co">#item per DIF</span></span></code></pre></div>
<p>Definiamo poi la struttura fattoriale, come già fatto in precedenza.</p>
<div class="sourceCode" id="cb97"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb97-1"><a href="differential-item-functioning-per-item-politomici.html#cb97-1" tabindex="-1"></a>fct.str.DIF <span class="ot">&lt;-</span> <span class="fu">mirt.model</span>(<span class="st">&#39;F1 = 1-6&#39;</span>)</span></code></pre></div>
<p>Infine, creiamo un oggetto contenente il tipo di modello, per non doverlo inserire in ogni passaggio.</p>
<div class="sourceCode" id="cb98"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb98-1"><a href="differential-item-functioning-per-item-politomici.html#cb98-1" tabindex="-1"></a>tipo.mod<span class="ot">&lt;-</span><span class="st">&#39;graded&#39;</span>  </span></code></pre></div>
<div id="stima-dei-parametri-nei-due-gruppi-1" class="section level4 hasAnchor">
<h4>Stima dei parametri nei due gruppi<a href="differential-item-functioning-per-item-politomici.html#stima-dei-parametri-nei-due-gruppi-1" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Procediamo alla stima dei parametri degli item nel gruppo di maschi inserendo l’etichetta ‘1’ all’interno della voce GRUPPO (<code>GRUPPO==1</code>).</p>
<div class="sourceCode" id="cb99"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb99-1"><a href="differential-item-functioning-per-item-politomici.html#cb99-1" tabindex="-1"></a>mod.group1<span class="ot">&lt;-</span><span class="fu">filter</span>(item.DIF.graded, GRUPPO<span class="sc">==</span><span class="st">&#39;1&#39;</span>)<span class="sc">%&gt;%</span>    <span class="co">#Inserire il gruppo</span></span>
<span id="cb99-2"><a href="differential-item-functioning-per-item-politomici.html#cb99-2" tabindex="-1"></a>  <span class="fu">mirt</span>(<span class="at">model=</span>fct.str.DIF, <span class="at">itemtype =</span> tipo.mod) </span></code></pre></div>
<pre><code>## 
Iteration: 1, Log-Lik: -2258.829, Max-Change: 1.87997
Iteration: 2, Log-Lik: -2204.298, Max-Change: 0.71480
Iteration: 3, Log-Lik: -2190.205, Max-Change: 0.25293
Iteration: 4, Log-Lik: -2185.405, Max-Change: 0.17363
Iteration: 5, Log-Lik: -2183.512, Max-Change: 0.13165
Iteration: 6, Log-Lik: -2182.675, Max-Change: 0.09156
Iteration: 7, Log-Lik: -2182.133, Max-Change: 0.06461
Iteration: 8, Log-Lik: -2182.007, Max-Change: 0.03479
Iteration: 9, Log-Lik: -2181.939, Max-Change: 0.02677
Iteration: 10, Log-Lik: -2181.867, Max-Change: 0.01570
Iteration: 11, Log-Lik: -2181.852, Max-Change: 0.00664
Iteration: 12, Log-Lik: -2181.844, Max-Change: 0.00561
Iteration: 13, Log-Lik: -2181.837, Max-Change: 0.00298
Iteration: 14, Log-Lik: -2181.834, Max-Change: 0.00202
Iteration: 15, Log-Lik: -2181.833, Max-Change: 0.00175
Iteration: 16, Log-Lik: -2181.831, Max-Change: 0.00090
Iteration: 17, Log-Lik: -2181.831, Max-Change: 0.00106
Iteration: 18, Log-Lik: -2181.831, Max-Change: 0.00069
Iteration: 19, Log-Lik: -2181.830, Max-Change: 0.00067
Iteration: 20, Log-Lik: -2181.830, Max-Change: 0.00058
Iteration: 21, Log-Lik: -2181.830, Max-Change: 0.00051
Iteration: 22, Log-Lik: -2181.830, Max-Change: 0.00011
Iteration: 23, Log-Lik: -2181.830, Max-Change: 0.00033
Iteration: 24, Log-Lik: -2181.830, Max-Change: 0.00036
Iteration: 25, Log-Lik: -2181.830, Max-Change: 0.00013
Iteration: 26, Log-Lik: -2181.830, Max-Change: 0.00028
Iteration: 27, Log-Lik: -2181.830, Max-Change: 0.00010</code></pre>
<div class="sourceCode" id="cb101"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb101-1"><a href="differential-item-functioning-per-item-politomici.html#cb101-1" tabindex="-1"></a><span class="fu">coef</span>(mod.group1, <span class="at">simplify=</span><span class="cn">TRUE</span>, <span class="at">IRTpars=</span>T)    <span class="co">#stampa dei parametri </span></span></code></pre></div>
<pre><code>## $items
##                 a    b1    b2    b3    b4
## ITEM_POLY_1 1.650 0.164 1.240 2.184 2.874
## ITEM_POLY_2 2.636 0.181 1.107 2.087 3.325
## ITEM_POLY_3 1.302 0.670 1.736 2.668 3.451
## ITEM_POLY_4 1.481 0.343 1.427 2.316 3.348
## ITEM_POLY_5 2.404 0.922 1.686 2.395 3.482
## ITEM_POLY_6 1.651 0.576 1.589 2.398 3.241
## 
## $means
## F1 
##  0 
## 
## $cov
##    F1
## F1  1</code></pre>
<p>Stimiamo poi i parametri nel gruppo delle femmine (<code>GRUPPO==2</code>).</p>
<div class="sourceCode" id="cb103"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb103-1"><a href="differential-item-functioning-per-item-politomici.html#cb103-1" tabindex="-1"></a>mod.group2<span class="ot">&lt;-</span><span class="fu">filter</span>(item.DIF.graded, GRUPPO<span class="sc">==</span><span class="st">&#39;2&#39;</span>)<span class="sc">%&gt;%</span>    <span class="co">#Inserire il gruppo</span></span>
<span id="cb103-2"><a href="differential-item-functioning-per-item-politomici.html#cb103-2" tabindex="-1"></a>  <span class="fu">mirt</span>(<span class="at">model=</span>fct.str.DIF, <span class="at">itemtype =</span> tipo.mod) </span></code></pre></div>
<pre><code>## 
Iteration: 1, Log-Lik: -2371.369, Max-Change: 1.15938
Iteration: 2, Log-Lik: -2308.183, Max-Change: 0.68798
Iteration: 3, Log-Lik: -2290.871, Max-Change: 0.46868
Iteration: 4, Log-Lik: -2284.622, Max-Change: 0.27333
Iteration: 5, Log-Lik: -2282.229, Max-Change: 0.17879
Iteration: 6, Log-Lik: -2281.174, Max-Change: 0.09382
Iteration: 7, Log-Lik: -2280.624, Max-Change: 0.06485
Iteration: 8, Log-Lik: -2280.391, Max-Change: 0.04768
Iteration: 9, Log-Lik: -2280.259, Max-Change: 0.03492
Iteration: 10, Log-Lik: -2280.109, Max-Change: 0.01516
Iteration: 11, Log-Lik: -2280.086, Max-Change: 0.01008
Iteration: 12, Log-Lik: -2280.070, Max-Change: 0.00740
Iteration: 13, Log-Lik: -2280.058, Max-Change: 0.00863
Iteration: 14, Log-Lik: -2280.051, Max-Change: 0.00441
Iteration: 15, Log-Lik: -2280.046, Max-Change: 0.00350
Iteration: 16, Log-Lik: -2280.037, Max-Change: 0.00182
Iteration: 17, Log-Lik: -2280.036, Max-Change: 0.00137
Iteration: 18, Log-Lik: -2280.036, Max-Change: 0.00169
Iteration: 19, Log-Lik: -2280.035, Max-Change: 0.00107
Iteration: 20, Log-Lik: -2280.035, Max-Change: 0.00082
Iteration: 21, Log-Lik: -2280.035, Max-Change: 0.00065
Iteration: 22, Log-Lik: -2280.034, Max-Change: 0.00048
Iteration: 23, Log-Lik: -2280.034, Max-Change: 0.00032
Iteration: 24, Log-Lik: -2280.034, Max-Change: 0.00042
Iteration: 25, Log-Lik: -2280.034, Max-Change: 0.00030
Iteration: 26, Log-Lik: -2280.034, Max-Change: 0.00038
Iteration: 27, Log-Lik: -2280.034, Max-Change: 0.00029
Iteration: 28, Log-Lik: -2280.034, Max-Change: 0.00017
Iteration: 29, Log-Lik: -2280.034, Max-Change: 0.00030
Iteration: 30, Log-Lik: -2280.034, Max-Change: 0.00016
Iteration: 31, Log-Lik: -2280.034, Max-Change: 0.00011
Iteration: 32, Log-Lik: -2280.034, Max-Change: 0.00029
Iteration: 33, Log-Lik: -2280.034, Max-Change: 0.00010
Iteration: 34, Log-Lik: -2280.034, Max-Change: 0.00037
Iteration: 35, Log-Lik: -2280.034, Max-Change: 0.00030
Iteration: 36, Log-Lik: -2280.034, Max-Change: 0.00035
Iteration: 37, Log-Lik: -2280.034, Max-Change: 0.00022
Iteration: 38, Log-Lik: -2280.034, Max-Change: 0.00026
Iteration: 39, Log-Lik: -2280.034, Max-Change: 0.00021
Iteration: 40, Log-Lik: -2280.034, Max-Change: 0.00011
Iteration: 41, Log-Lik: -2280.034, Max-Change: 0.00024
Iteration: 42, Log-Lik: -2280.034, Max-Change: 0.00011
Iteration: 43, Log-Lik: -2280.034, Max-Change: 0.00007</code></pre>
<div class="sourceCode" id="cb105"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb105-1"><a href="differential-item-functioning-per-item-politomici.html#cb105-1" tabindex="-1"></a><span class="fu">coef</span>(mod.group2, <span class="at">simplify=</span><span class="cn">TRUE</span>, <span class="at">IRTpars=</span>T)    <span class="co">#stampa dei parametri</span></span></code></pre></div>
<pre><code>## $items
##                 a    b1    b2    b3    b4
## ITEM_POLY_1 1.737 0.181 1.160 2.033 2.594
## ITEM_POLY_2 2.966 0.221 1.049 1.717 2.348
## ITEM_POLY_3 1.428 0.401 1.199 2.184 3.246
## ITEM_POLY_4 1.948 0.319 1.089 1.853 2.608
## ITEM_POLY_5 2.177 0.771 1.604 2.200 2.812
## ITEM_POLY_6 1.189 0.862 2.036 3.338 4.030
## 
## $means
## F1 
##  0 
## 
## $cov
##    F1
## F1  1</code></pre>
</div>
<div id="primo-step-della-procedura-di-purificazione-1" class="section level4 hasAnchor">
<h4>Primo step della procedura di purificazione<a href="differential-item-functioning-per-item-politomici.html#primo-step-della-procedura-di-purificazione-1" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Procediamo poi con il primo step della procedura di purificazione, stimando un modello di partenza tramite la funzione <code>multiplegroup()</code>, dove nell’ argomento <code>invariance =c()</code> provvederemo a:</p>
<ul>
<li><p>vincolare i parametri degli item essere uguali nei due gruppi (<code>colnames(item.DIF.graded)</code>);</p></li>
<li><p>Fissare le medie a 0 nel gruppo di riferimento e a lasciarle libere nel gruppo focale (<code>'free_means'</code>);</p></li>
<li><p>Fissare le varianze a 1 nel gruppo di riferimento e a lasciarle libere nel gruppo focale (<code>'free_var'</code> );</p></li>
</ul>
<div class="sourceCode" id="cb107"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb107-1"><a href="differential-item-functioning-per-item-politomici.html#cb107-1" tabindex="-1"></a><span class="co">#Primo step della procedura di purificazione.</span></span>
<span id="cb107-2"><a href="differential-item-functioning-per-item-politomici.html#cb107-2" tabindex="-1"></a><span class="co">#Stima del modello di partenza</span></span>
<span id="cb107-3"><a href="differential-item-functioning-per-item-politomici.html#cb107-3" tabindex="-1"></a></span>
<span id="cb107-4"><a href="differential-item-functioning-per-item-politomici.html#cb107-4" tabindex="-1"></a>mod.dif<span class="fl">.1</span><span class="ot">&lt;-</span><span class="fu">multipleGroup</span>(item.DIF.graded,<span class="at">model=</span>fct.str.DIF,</span>
<span id="cb107-5"><a href="differential-item-functioning-per-item-politomici.html#cb107-5" tabindex="-1"></a>                         <span class="at">itemtype =</span>tipo.mod,<span class="at">group =</span>GRUPPO,<span class="at">SE=</span><span class="cn">TRUE</span>,</span>
<span id="cb107-6"><a href="differential-item-functioning-per-item-politomici.html#cb107-6" tabindex="-1"></a>                         <span class="at">invariance =</span> <span class="fu">c</span>(<span class="fu">colnames</span>(item.DIF.graded),</span>
<span id="cb107-7"><a href="differential-item-functioning-per-item-politomici.html#cb107-7" tabindex="-1"></a>                                        <span class="st">&#39;free_means&#39;</span>, <span class="st">&#39;free_var&#39;</span>))</span></code></pre></div>
<pre><code>## 
Iteration: 1, Log-Lik: -4645.078, Max-Change: 1.24819
Iteration: 2, Log-Lik: -4513.557, Max-Change: 0.70263
Iteration: 3, Log-Lik: -4489.304, Max-Change: 0.37508
Iteration: 4, Log-Lik: -4483.992, Max-Change: 0.23986
Iteration: 5, Log-Lik: -4482.128, Max-Change: 0.14803
Iteration: 6, Log-Lik: -4481.215, Max-Change: 0.11593
Iteration: 7, Log-Lik: -4480.128, Max-Change: 0.06541
Iteration: 8, Log-Lik: -4479.787, Max-Change: 0.04103
Iteration: 9, Log-Lik: -4479.561, Max-Change: 0.03151
Iteration: 10, Log-Lik: -4479.277, Max-Change: 0.03881
Iteration: 11, Log-Lik: -4479.129, Max-Change: 0.02506
Iteration: 12, Log-Lik: -4479.026, Max-Change: 0.01979
Iteration: 13, Log-Lik: -4478.876, Max-Change: 0.04245
Iteration: 14, Log-Lik: -4478.734, Max-Change: 0.01965
Iteration: 15, Log-Lik: -4478.691, Max-Change: 0.01274
Iteration: 16, Log-Lik: -4478.660, Max-Change: 0.01060
Iteration: 17, Log-Lik: -4478.639, Max-Change: 0.00832
Iteration: 18, Log-Lik: -4478.622, Max-Change: 0.00712
Iteration: 19, Log-Lik: -4478.597, Max-Change: 0.01722
Iteration: 20, Log-Lik: -4478.570, Max-Change: 0.00782
Iteration: 21, Log-Lik: -4478.563, Max-Change: 0.00498
Iteration: 22, Log-Lik: -4478.558, Max-Change: 0.00395
Iteration: 23, Log-Lik: -4478.554, Max-Change: 0.00318
Iteration: 24, Log-Lik: -4478.552, Max-Change: 0.00274
Iteration: 25, Log-Lik: -4478.547, Max-Change: 0.00677
Iteration: 26, Log-Lik: -4478.543, Max-Change: 0.00307
Iteration: 27, Log-Lik: -4478.542, Max-Change: 0.00195
Iteration: 28, Log-Lik: -4478.541, Max-Change: 0.00156
Iteration: 29, Log-Lik: -4478.540, Max-Change: 0.00126
Iteration: 30, Log-Lik: -4478.540, Max-Change: 0.00108
Iteration: 31, Log-Lik: -4478.539, Max-Change: 0.00272
Iteration: 32, Log-Lik: -4478.539, Max-Change: 0.00122
Iteration: 33, Log-Lik: -4478.538, Max-Change: 0.00079
Iteration: 34, Log-Lik: -4478.538, Max-Change: 0.00064
Iteration: 35, Log-Lik: -4478.538, Max-Change: 0.00051
Iteration: 36, Log-Lik: -4478.538, Max-Change: 0.00044
Iteration: 37, Log-Lik: -4478.538, Max-Change: 0.00109
Iteration: 38, Log-Lik: -4478.538, Max-Change: 0.00049
Iteration: 39, Log-Lik: -4478.538, Max-Change: 0.00031
Iteration: 40, Log-Lik: -4478.538, Max-Change: 0.00028
Iteration: 41, Log-Lik: -4478.538, Max-Change: 0.00021
Iteration: 42, Log-Lik: -4478.538, Max-Change: 0.00018
Iteration: 43, Log-Lik: -4478.538, Max-Change: 0.00044
Iteration: 44, Log-Lik: -4478.538, Max-Change: 0.00019
Iteration: 45, Log-Lik: -4478.538, Max-Change: 0.00013
Iteration: 46, Log-Lik: -4478.538, Max-Change: 0.00012
Iteration: 47, Log-Lik: -4478.538, Max-Change: 0.00008
## 
## Calculating information matrix...</code></pre>
<p>A partire da questo modello, procediamo a stimare il DIF al primo step di interazione tramite la funzione <code>DIF()</code>. Impostando la voce <code>scheme='drop'</code>, procediamo rimuovendo i vincoli degli item uno ad uno per essere confrontati tramite il Chi-Quadro nei due gruppi.</p>
<p>Primamariamente, verifichiamo la possibile presenza di DIF nei parametri <em>a</em> (<code>which.par = 'a1'</code>)</p>
<div class="sourceCode" id="cb109"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb109-1"><a href="differential-item-functioning-per-item-politomici.html#cb109-1" tabindex="-1"></a><span class="co">#DIF in a al primo step di purificazione</span></span>
<span id="cb109-2"><a href="differential-item-functioning-per-item-politomici.html#cb109-2" tabindex="-1"></a></span>
<span id="cb109-3"><a href="differential-item-functioning-per-item-politomici.html#cb109-3" tabindex="-1"></a><span class="fu">DIF</span>(mod.dif<span class="fl">.1</span>,<span class="at">which.par =</span> <span class="st">&#39;a1&#39;</span>, <span class="at">simplify =</span> <span class="cn">TRUE</span>, <span class="at">scheme =</span> <span class="st">&#39;drop&#39;</span>)</span></code></pre></div>
<pre><code>##             converged    AIC  SABIC     HQ    BIC    X2 df     p
## ITEM_POLY_1      TRUE  1.750  3.246  3.545  6.422  0.25  1 0.617
## ITEM_POLY_2      TRUE  1.837  3.334  3.633  6.509 0.163  1 0.687
## ITEM_POLY_3      TRUE  0.664  2.161  2.460  5.336 1.336  1 0.248
## ITEM_POLY_4      TRUE  0.467  1.963  2.263  5.139 1.533  1 0.216
## ITEM_POLY_5      TRUE  1.952  3.449  3.748  6.624 0.048  1 0.827
## ITEM_POLY_6      TRUE -7.632 -6.135 -5.836 -2.960 9.632  1 0.002</code></pre>
<p>Per quanto riguarda la capacità discriminativa, l’item 6 mostrava DIF al primo step di purificazione (<span class="math inline">\(X^2\)</span>(1)=9.63 , <em>p</em> &lt; .01).</p>
<p>Proseguiamo poi con la stima del DIF relativo alle soglie. Come per il modello 2PL anche in questo caso va utilizzato il parametro <em>d</em>. Inoltre, inserendo nella funzione <code>which.par =c('d1', 'd2','d3','d4')</code> andiamo a analizzare il DIF nelle soglie congiuntamente.</p>
<div class="sourceCode" id="cb111"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb111-1"><a href="differential-item-functioning-per-item-politomici.html#cb111-1" tabindex="-1"></a><span class="co">#DIF in a al primo step di purificazione</span></span>
<span id="cb111-2"><a href="differential-item-functioning-per-item-politomici.html#cb111-2" tabindex="-1"></a></span>
<span id="cb111-3"><a href="differential-item-functioning-per-item-politomici.html#cb111-3" tabindex="-1"></a><span class="fu">DIF</span>(mod.dif<span class="fl">.1</span>,<span class="at">which.par =</span><span class="fu">c</span>(<span class="st">&#39;d1&#39;</span>, <span class="st">&#39;d2&#39;</span>,<span class="st">&#39;d3&#39;</span>,<span class="st">&#39;d4&#39;</span>),</span>
<span id="cb111-4"><a href="differential-item-functioning-per-item-politomici.html#cb111-4" tabindex="-1"></a>    <span class="at">simplify =</span> <span class="cn">TRUE</span>, <span class="at">scheme =</span> <span class="st">&#39;drop&#39;</span>)</span></code></pre></div>
<pre><code>##             converged    AIC  SABIC     HQ    BIC    X2 df     p
## ITEM_POLY_1      TRUE  7.579 13.565 14.763 26.267 0.421  4 0.981
## ITEM_POLY_2      TRUE  1.404  7.390  8.587 20.092 6.596  4 0.159
## ITEM_POLY_3      TRUE -0.431  5.555  6.753 18.257 8.431  4 0.077
## ITEM_POLY_4      TRUE  6.801 12.787 13.984 25.489 1.199  4 0.878
## ITEM_POLY_5      TRUE  4.346 10.332 11.529 23.034 3.654  4 0.455
## ITEM_POLY_6      TRUE  2.096  8.082  9.279 20.784 5.904  4 0.206</code></pre>
<p>Per quanto riguarda le soglie, nessun item mostrava DIF.</p>
</div>
<div id="secondo-step-della-procedura-di-purificazione-1" class="section level4 hasAnchor">
<h4>Secondo step della procedura di purificazione<a href="differential-item-functioning-per-item-politomici.html#secondo-step-della-procedura-di-purificazione-1" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Procediamo quindi con il secondo step della procedura di purificazione per confermare la possibile presenza di DIF nella capacità discriminativa dell’item 6.</p>
<p>Innanzitutto, definiamo gli item ancora.</p>
<div class="sourceCode" id="cb113"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb113-1"><a href="differential-item-functioning-per-item-politomici.html#cb113-1" tabindex="-1"></a><span class="co">#Definisco gli item ancora  </span></span>
<span id="cb113-2"><a href="differential-item-functioning-per-item-politomici.html#cb113-2" tabindex="-1"></a></span>
<span id="cb113-3"><a href="differential-item-functioning-per-item-politomici.html#cb113-3" tabindex="-1"></a>itemnames <span class="ot">&lt;-</span> <span class="fu">colnames</span>(item.DIF.graded) </span>
<span id="cb113-4"><a href="differential-item-functioning-per-item-politomici.html#cb113-4" tabindex="-1"></a>item.ancora<span class="ot">&lt;-</span> itemnames[<span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">5</span>)] <span class="co">#Inserire gli item ancora</span></span>
<span id="cb113-5"><a href="differential-item-functioning-per-item-politomici.html#cb113-5" tabindex="-1"></a><span class="fu">print</span>(item.ancora)</span></code></pre></div>
<pre><code>## [1] &quot;ITEM_POLY_1&quot; &quot;ITEM_POLY_2&quot; &quot;ITEM_POLY_3&quot; &quot;ITEM_POLY_4&quot; &quot;ITEM_POLY_5&quot;</code></pre>
<p>Proseguiamo poi creando un oggetto che contenga l’item candidato, ovvero il sesto.</p>
<div class="sourceCode" id="cb115"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb115-1"><a href="differential-item-functioning-per-item-politomici.html#cb115-1" tabindex="-1"></a><span class="co">#Definisco gli item candidati</span></span>
<span id="cb115-2"><a href="differential-item-functioning-per-item-politomici.html#cb115-2" tabindex="-1"></a></span>
<span id="cb115-3"><a href="differential-item-functioning-per-item-politomici.html#cb115-3" tabindex="-1"></a>item.candidati<span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">6</span>)  <span class="co">#Inserire gli item candidati </span></span>
<span id="cb115-4"><a href="differential-item-functioning-per-item-politomici.html#cb115-4" tabindex="-1"></a><span class="fu">print</span>(item.candidati) </span></code></pre></div>
<pre><code>## [1] 6</code></pre>
<p>Procediamo poi a creare un nuovo modello tramite la funzione <code>multiplegroup()</code> con i seguenti vincoli all’interno dell’argomento <code>invariance=c()</code>:</p>
<ul>
<li><p>i parametri degli item ancora fissati ad essere uguali nei due gruppi;</p></li>
<li><p>le medie e le varianze fissate a 0 e 1 nel gruppo focale e libere di essere stimate nel gruppo di riferimento.</p></li>
</ul>
<div class="sourceCode" id="cb117"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb117-1"><a href="differential-item-functioning-per-item-politomici.html#cb117-1" tabindex="-1"></a><span class="co">#Secondo step della procedura di purificazione.</span></span>
<span id="cb117-2"><a href="differential-item-functioning-per-item-politomici.html#cb117-2" tabindex="-1"></a><span class="co">#Stima del modello</span></span>
<span id="cb117-3"><a href="differential-item-functioning-per-item-politomici.html#cb117-3" tabindex="-1"></a></span>
<span id="cb117-4"><a href="differential-item-functioning-per-item-politomici.html#cb117-4" tabindex="-1"></a>mod.dif<span class="fl">.2</span><span class="ot">&lt;-</span><span class="fu">multipleGroup</span>(item.DIF.graded,<span class="at">model=</span>fct.str.DIF,</span>
<span id="cb117-5"><a href="differential-item-functioning-per-item-politomici.html#cb117-5" tabindex="-1"></a>                         <span class="at">itemtype =</span>tipo.mod,<span class="at">group =</span>GRUPPO,<span class="at">SE=</span><span class="cn">TRUE</span>,</span>
<span id="cb117-6"><a href="differential-item-functioning-per-item-politomici.html#cb117-6" tabindex="-1"></a>                         <span class="at">invariance =</span> <span class="fu">c</span>(item.ancora,</span>
<span id="cb117-7"><a href="differential-item-functioning-per-item-politomici.html#cb117-7" tabindex="-1"></a>                                        <span class="st">&#39;free_means&#39;</span>, <span class="st">&#39;free_var&#39;</span>))</span></code></pre></div>
<pre><code>## 
Iteration: 1, Log-Lik: -4645.078, Max-Change: 1.25701
Iteration: 2, Log-Lik: -4508.369, Max-Change: 0.70537
Iteration: 3, Log-Lik: -4481.891, Max-Change: 0.39169
Iteration: 4, Log-Lik: -4476.329, Max-Change: 0.23777
Iteration: 5, Log-Lik: -4474.665, Max-Change: 0.14305
Iteration: 6, Log-Lik: -4473.974, Max-Change: 0.11154
Iteration: 7, Log-Lik: -4473.249, Max-Change: 0.05102
Iteration: 8, Log-Lik: -4473.034, Max-Change: 0.03419
Iteration: 9, Log-Lik: -4472.881, Max-Change: 0.02755
Iteration: 10, Log-Lik: -4472.658, Max-Change: 0.04140
Iteration: 11, Log-Lik: -4472.538, Max-Change: 0.02394
Iteration: 12, Log-Lik: -4472.467, Max-Change: 0.01826
Iteration: 13, Log-Lik: -4472.364, Max-Change: 0.02813
Iteration: 14, Log-Lik: -4472.305, Max-Change: 0.01578
Iteration: 15, Log-Lik: -4472.273, Max-Change: 0.01187
Iteration: 16, Log-Lik: -4472.230, Max-Change: 0.01645
Iteration: 17, Log-Lik: -4472.206, Max-Change: 0.00989
Iteration: 18, Log-Lik: -4472.192, Max-Change: 0.00770
Iteration: 19, Log-Lik: -4472.170, Max-Change: 0.01314
Iteration: 20, Log-Lik: -4472.156, Max-Change: 0.00704
Iteration: 21, Log-Lik: -4472.149, Max-Change: 0.00517
Iteration: 22, Log-Lik: -4472.141, Max-Change: 0.00631
Iteration: 23, Log-Lik: -4472.137, Max-Change: 0.00411
Iteration: 24, Log-Lik: -4472.134, Max-Change: 0.00333
Iteration: 25, Log-Lik: -4472.130, Max-Change: 0.00739
Iteration: 26, Log-Lik: -4472.125, Max-Change: 0.00345
Iteration: 27, Log-Lik: -4472.124, Max-Change: 0.00232
Iteration: 28, Log-Lik: -4472.123, Max-Change: 0.00210
Iteration: 29, Log-Lik: -4472.122, Max-Change: 0.00161
Iteration: 30, Log-Lik: -4472.122, Max-Change: 0.00138
Iteration: 31, Log-Lik: -4472.121, Max-Change: 0.00341
Iteration: 32, Log-Lik: -4472.120, Max-Change: 0.00154
Iteration: 33, Log-Lik: -4472.119, Max-Change: 0.00101
Iteration: 34, Log-Lik: -4472.119, Max-Change: 0.00087
Iteration: 35, Log-Lik: -4472.119, Max-Change: 0.00068
Iteration: 36, Log-Lik: -4472.119, Max-Change: 0.00059
Iteration: 37, Log-Lik: -4472.119, Max-Change: 0.00145
Iteration: 38, Log-Lik: -4472.119, Max-Change: 0.00065
Iteration: 39, Log-Lik: -4472.119, Max-Change: 0.00043
Iteration: 40, Log-Lik: -4472.119, Max-Change: 0.00038
Iteration: 41, Log-Lik: -4472.119, Max-Change: 0.00029
Iteration: 42, Log-Lik: -4472.119, Max-Change: 0.00025
Iteration: 43, Log-Lik: -4472.119, Max-Change: 0.00060
Iteration: 44, Log-Lik: -4472.119, Max-Change: 0.00028
Iteration: 45, Log-Lik: -4472.119, Max-Change: 0.00018
Iteration: 46, Log-Lik: -4472.119, Max-Change: 0.00017
Iteration: 47, Log-Lik: -4472.119, Max-Change: 0.00013
Iteration: 48, Log-Lik: -4472.119, Max-Change: 0.00011
Iteration: 49, Log-Lik: -4472.119, Max-Change: 0.00025
Iteration: 50, Log-Lik: -4472.119, Max-Change: 0.00011
Iteration: 51, Log-Lik: -4472.119, Max-Change: 0.00008
## 
## Calculating information matrix...</code></pre>
<p>Stiamiamo ora il DIF nella capacità discriminativa del solo item 6, utilizzando lo schema <code>'add'</code>.</p>
<div class="sourceCode" id="cb119"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb119-1"><a href="differential-item-functioning-per-item-politomici.html#cb119-1" tabindex="-1"></a><span class="co">#DIF in a al secondo step di purificazione  </span></span>
<span id="cb119-2"><a href="differential-item-functioning-per-item-politomici.html#cb119-2" tabindex="-1"></a></span>
<span id="cb119-3"><a href="differential-item-functioning-per-item-politomici.html#cb119-3" tabindex="-1"></a><span class="fu">DIF</span>(mod.dif<span class="fl">.2</span>,<span class="at">which.par =</span> <span class="st">&#39;a1&#39;</span>, <span class="at">simplify =</span> <span class="cn">TRUE</span>, </span>
<span id="cb119-4"><a href="differential-item-functioning-per-item-politomici.html#cb119-4" tabindex="-1"></a>    <span class="at">scheme =</span> <span class="st">&#39;add&#39;</span>, <span class="at">items2test =</span> item.candidati)</span></code></pre></div>
<pre><code>##             converged    AIC  SABIC     HQ    BIC    X2 df     p
## ITEM_POLY_6      TRUE -4.934 -3.438 -3.138 -0.262 6.934  1 0.008</code></pre>
<p>Il DIF nella capacità discrimiativa dell’item 6 è stato confermato anche al secondo step della procedura di purificazione (<span class="math inline">\(X^2\)</span>(1)=6.93 , <em>p</em> &lt; .01), ad indicare che l’item riusultava essere discriminare meglio le differenze di tratto nei maschi (<em>a</em>=1.65) rispetto alle femmine (<em>a</em>=1.19).</p>
<p>Questo può essere anche analizzato graficamente tramite la funzione <code>itemplot()</code>.</p>
<div class="sourceCode" id="cb121"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb121-1"><a href="differential-item-functioning-per-item-politomici.html#cb121-1" tabindex="-1"></a><span class="fu">itemplot</span>(mod.dif<span class="fl">.2</span>, <span class="at">item=</span><span class="dv">6</span>, </span>
<span id="cb121-2"><a href="differential-item-functioning-per-item-politomici.html#cb121-2" tabindex="-1"></a>         <span class="at">type=</span><span class="st">&#39;trace&#39;</span>, <span class="at">theta_lim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">3</span>, <span class="dv">3</span>)) </span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-67-1.png" width="672" /></p>
</div>
<div id="effect-size-del-dif-1" class="section level4 hasAnchor">
<h4>Effect size del DIF<a href="differential-item-functioning-per-item-politomici.html#effect-size-del-dif-1" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Verifichiamo ora l’effect size del DIF nel parametro dell’item 6, tramite la procdura descritta da <a href="https://pubmed.ncbi.nlm.nih.gov/20604592/">Meade (2010)</a>.</p>
<p><strong>Effect size a livello di item</strong></p>
<p>In primo luogo valutiamo l’effect size a livello di item, tramite gli indici e l’ispezione grafica.</p>
<div class="sourceCode" id="cb122"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb122-1"><a href="differential-item-functioning-per-item-politomici.html#cb122-1" tabindex="-1"></a><span class="co">#Effect size al livello degli item</span></span>
<span id="cb122-2"><a href="differential-item-functioning-per-item-politomici.html#cb122-2" tabindex="-1"></a></span>
<span id="cb122-3"><a href="differential-item-functioning-per-item-politomici.html#cb122-3" tabindex="-1"></a><span class="co">#Indici</span></span>
<span id="cb122-4"><a href="differential-item-functioning-per-item-politomici.html#cb122-4" tabindex="-1"></a><span class="fu">empirical_ES</span>(mod.dif<span class="fl">.2</span>)              </span></code></pre></div>
<pre><code>##          SIDS  UIDS SIDN  UIDN   ESSD theta.of.max.D max.D mean.ES.foc mean.ES.ref
## item.1  0.000 0.000  0.0 0.000  0.000         -1.227  0.00       0.746       0.746
## item.2  0.000 0.000  0.0 0.000  0.000         -1.227  0.00       0.674       0.674
## item.3  0.000 0.000  0.0 0.000  0.000         -1.227  0.00       0.639       0.639
## item.4  0.000 0.000  0.0 0.000  0.000         -1.227  0.00       0.691       0.691
## item.5  0.000 0.000  0.0 0.000  0.000         -1.227  0.00       0.392       0.392
## item.6 -0.109 0.173 -0.1 0.155 -0.219          2.964 -1.11       0.463       0.572</code></pre>
<div class="sourceCode" id="cb124"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb124-1"><a href="differential-item-functioning-per-item-politomici.html#cb124-1" tabindex="-1"></a><span class="co">#Grafici </span></span>
<span id="cb124-2"><a href="differential-item-functioning-per-item-politomici.html#cb124-2" tabindex="-1"></a><span class="fu">empirical_ES</span>(mod.dif<span class="fl">.2</span>, <span class="at">plot =</span> <span class="cn">TRUE</span>) </span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-68-1.png" width="672" /></p>
<p><strong>Effect size a livello di test</strong></p>
<p>Proseguiamo verificando l’impatto del DIF sull’intero test.</p>
<div class="sourceCode" id="cb125"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb125-1"><a href="differential-item-functioning-per-item-politomici.html#cb125-1" tabindex="-1"></a><span class="co">#Effect Size a livello del test</span></span>
<span id="cb125-2"><a href="differential-item-functioning-per-item-politomici.html#cb125-2" tabindex="-1"></a></span>
<span id="cb125-3"><a href="differential-item-functioning-per-item-politomici.html#cb125-3" tabindex="-1"></a><span class="co">#Indici</span></span>
<span id="cb125-4"><a href="differential-item-functioning-per-item-politomici.html#cb125-4" tabindex="-1"></a><span class="fu">empirical_ES</span>(mod.dif<span class="fl">.2</span>, <span class="at">DIF =</span> <span class="cn">FALSE</span>)               </span></code></pre></div>
<pre><code>##           Effect Size       Value
## 1                STDS -0.10917912
## 2                UTDS  0.17281302
## 3              UETSDS  0.17281302
## 4               ETSSD -0.03021414
## 5         Starks.DTFR -0.10014410
## 6               UDTFR  0.15479671
## 7              UETSDN  0.15479671
## 8 theta.of.max.test.D  2.96352763
## 9           Test.Dmax -1.11033082</code></pre>
<div class="sourceCode" id="cb127"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb127-1"><a href="differential-item-functioning-per-item-politomici.html#cb127-1" tabindex="-1"></a><span class="co">#Grafici</span></span>
<span id="cb127-2"><a href="differential-item-functioning-per-item-politomici.html#cb127-2" tabindex="-1"></a><span class="fu">empirical_ES</span>(mod.dif<span class="fl">.2</span>, <span class="at">DIF =</span> <span class="cn">FALSE</span>, <span class="at">plot =</span> <span class="cn">TRUE</span>) </span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-69-1.png" width="672" /></p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="calibrazione-di-strumenti-unidimensionali-con-item-politomici.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="scoring-di-strumenti-unidimensionali-politomici.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/USERNAME/REPO/edit/BRANCH/07-DIF-politomici.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["_main.pdf", "_main.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
